# This is a basic workflow to help you get started with Actions

name: Deloy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    # hexo branch的push事件
    branches: [ hexo ]
  schedule:
    # 定时任务，整点
    - cron: '0 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ubuntu-latest
        node-version: 12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # check env version
    - name: check node version
      run: node --version
    
    - name: check npm version
      run: npm --version
    
    - name: Setup Hexo env
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
      run: |
        node ./source/outlet/static/scripts/updateYiqing.js
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # set git infomation
        git config --global user.name 'hexo deployer'
        git config --global user.email '907138916@qq.com'
        # install package
        npm i
        # hexo clean && hexo g && hexo d
        npm run deploy
        cat ./public/index.html
